/*

```ts
// signUp
POST "/api/auth" 
body: { name,email, phone, password }

201: {message, token}
400: {message}
500: {message}
```
*/
POST http://localhost:5000/api/auth 
Content-Type: application/json

{
    "email": "0f76e3ass1016@emailbbox.pro",
    "password": "Possw0rd",
    "name":"qotayba",
    "phone":"70222333"
}
###
PUT http://localhost:5000/api/auth 
Content-Type: application/json

{
    "email": "0f76e3ass1016@emailbbox.pro",
    "password": "Possw0rd" 
} 
###
POST http://localhost:5000/api/auth/reset-password
Content-Type: application/json
{
    "email": "0f76e3assss1016@emailbbox.pro"
}
###

GET http://localhost:5000/api/test/app
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlmNDlmZDFiYjRjYmZjY2RkNjI3NWIiLCJlbWFpbCI6IjBmNzZlM2FzczEwMTZAZW1haWxiYm94LnBybyIsImlhdCI6MTcyMTc0NzE5MiwiZXhwIjoxNzIxNzUwNzkyfQ.86fE-AXnymrExBEcWVWvEJiGuGLTdwxafq2NQOEwhkg
###

GET http://localhost:5000/api/test/Controllers
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlmNDlmZDFiYjRjYmZjY2RkNjI3NWIiLCJlbWFpbCI6IjBmNzZlM2FzczEwMTZAZW1haWxiYm94LnBybyIsImlhdCI6MTcyMTc0NzE5MiwiZXhwIjoxNzIxNzUwNzkyfQ.86fE-AXnymrExBEcWVWvEJiGuGLTdwxafq2NQOEwhkg